<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/transaction.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.DeleteName</code>
 */
class DeleteName extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes registrant = 1;</code>
     */
    protected $registrant = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $registrant
     *     @type string $name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes registrant = 1;</code>
     * @return string
     */
    public function getRegistrant()
    {
        return $this->registrant;
    }

    /**
     * Generated from protobuf field <code>bytes registrant = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRegistrant($var)
    {
        GPBUtil::checkString($var, False);
        $this->registrant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

