<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/transaction.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.NanoPay</code>
 */
class NanoPay extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes sender = 1;</code>
     */
    protected $sender = '';
    /**
     * Generated from protobuf field <code>bytes recipient = 2;</code>
     */
    protected $recipient = '';
    /**
     * Generated from protobuf field <code>uint64 id = 3;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>int64 amount = 4;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>uint32 txn_expiration = 5;</code>
     */
    protected $txn_expiration = 0;
    /**
     * Generated from protobuf field <code>uint32 nano_pay_expiration = 6;</code>
     */
    protected $nano_pay_expiration = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sender
     *     @type string $recipient
     *     @type int|string $id
     *     @type int|string $amount
     *     @type int $txn_expiration
     *     @type int $nano_pay_expiration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes sender = 1;</code>
     * @return string
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * Generated from protobuf field <code>bytes sender = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSender($var)
    {
        GPBUtil::checkString($var, False);
        $this->sender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes recipient = 2;</code>
     * @return string
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * Generated from protobuf field <code>bytes recipient = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRecipient($var)
    {
        GPBUtil::checkString($var, False);
        $this->recipient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 3;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 4;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 txn_expiration = 5;</code>
     * @return int
     */
    public function getTxnExpiration()
    {
        return $this->txn_expiration;
    }

    /**
     * Generated from protobuf field <code>uint32 txn_expiration = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTxnExpiration($var)
    {
        GPBUtil::checkUint32($var);
        $this->txn_expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 nano_pay_expiration = 6;</code>
     * @return int
     */
    public function getNanoPayExpiration()
    {
        return $this->nano_pay_expiration;
    }

    /**
     * Generated from protobuf field <code>uint32 nano_pay_expiration = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setNanoPayExpiration($var)
    {
        GPBUtil::checkUint32($var);
        $this->nano_pay_expiration = $var;

        return $this;
    }

}

