<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/transaction.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.Program</code>
 */
class Program extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes code = 1;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>bytes parameter = 2;</code>
     */
    protected $parameter = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type string $parameter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>bytes code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, False);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes parameter = 2;</code>
     * @return string
     */
    public function getParameter()
    {
        return $this->parameter;
    }

    /**
     * Generated from protobuf field <code>bytes parameter = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParameter($var)
    {
        GPBUtil::checkString($var, False);
        $this->parameter = $var;

        return $this;
    }

}

