<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/sigchain.proto

namespace Protos;

use UnexpectedValueException;

/**
 * Protobuf type <code>protos.SigAlgo</code>
 */
class SigAlgo
{
    /**
     * Generated from protobuf enum <code>SIGNATURE = 0;</code>
     */
    const SIGNATURE = 0;
    /**
     * Generated from protobuf enum <code>VRF = 1;</code>
     */
    const VRF = 1;

    private static $valueToName = [
        self::SIGNATURE => 'SIGNATURE',
        self::VRF => 'VRF',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

