<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/sigchain.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.SigChain</code>
 */
class SigChain extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 nonce = 1;</code>
     */
    protected $nonce = 0;
    /**
     * Generated from protobuf field <code>uint32 data_size = 2;</code>
     */
    protected $data_size = 0;
    /**
     * Generated from protobuf field <code>bytes block_hash = 3;</code>
     */
    protected $block_hash = '';
    /**
     * Generated from protobuf field <code>bytes src_id = 4;</code>
     */
    protected $src_id = '';
    /**
     * Generated from protobuf field <code>bytes src_pubkey = 5;</code>
     */
    protected $src_pubkey = '';
    /**
     * Generated from protobuf field <code>bytes dest_id = 6;</code>
     */
    protected $dest_id = '';
    /**
     * Generated from protobuf field <code>bytes dest_pubkey = 7;</code>
     */
    protected $dest_pubkey = '';
    /**
     * Generated from protobuf field <code>repeated .protos.SigChainElem elems = 8;</code>
     */
    private $elems;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $nonce
     *     @type int $data_size
     *     @type string $block_hash
     *     @type string $src_id
     *     @type string $src_pubkey
     *     @type string $dest_id
     *     @type string $dest_pubkey
     *     @type \Protos\SigChainElem[]|\Google\Protobuf\Internal\RepeatedField $elems
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\Sigchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 nonce = 1;</code>
     * @return int
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * Generated from protobuf field <code>uint32 nonce = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkUint32($var);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 data_size = 2;</code>
     * @return int
     */
    public function getDataSize()
    {
        return $this->data_size;
    }

    /**
     * Generated from protobuf field <code>uint32 data_size = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDataSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->data_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes block_hash = 3;</code>
     * @return string
     */
    public function getBlockHash()
    {
        return $this->block_hash;
    }

    /**
     * Generated from protobuf field <code>bytes block_hash = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBlockHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->block_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes src_id = 4;</code>
     * @return string
     */
    public function getSrcId()
    {
        return $this->src_id;
    }

    /**
     * Generated from protobuf field <code>bytes src_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSrcId($var)
    {
        GPBUtil::checkString($var, False);
        $this->src_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes src_pubkey = 5;</code>
     * @return string
     */
    public function getSrcPubkey()
    {
        return $this->src_pubkey;
    }

    /**
     * Generated from protobuf field <code>bytes src_pubkey = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSrcPubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->src_pubkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes dest_id = 6;</code>
     * @return string
     */
    public function getDestId()
    {
        return $this->dest_id;
    }

    /**
     * Generated from protobuf field <code>bytes dest_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDestId($var)
    {
        GPBUtil::checkString($var, False);
        $this->dest_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes dest_pubkey = 7;</code>
     * @return string
     */
    public function getDestPubkey()
    {
        return $this->dest_pubkey;
    }

    /**
     * Generated from protobuf field <code>bytes dest_pubkey = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDestPubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->dest_pubkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.SigChainElem elems = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElems()
    {
        return $this->elems;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.SigChainElem elems = 8;</code>
     * @param \Protos\SigChainElem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\SigChainElem::class);
        $this->elems = $arr;

        return $this;
    }

}

