<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/transaction.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.SigChainTxn</code>
 */
class SigChainTxn extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes sigChain = 1;</code>
     */
    protected $sigChain = '';
    /**
     * Generated from protobuf field <code>bytes submitter = 2;</code>
     */
    protected $submitter = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sigChain
     *     @type string $submitter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes sigChain = 1;</code>
     * @return string
     */
    public function getSigChain()
    {
        return $this->sigChain;
    }

    /**
     * Generated from protobuf field <code>bytes sigChain = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSigChain($var)
    {
        GPBUtil::checkString($var, False);
        $this->sigChain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes submitter = 2;</code>
     * @return string
     */
    public function getSubmitter()
    {
        return $this->submitter;
    }

    /**
     * Generated from protobuf field <code>bytes submitter = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubmitter($var)
    {
        GPBUtil::checkString($var, False);
        $this->submitter = $var;

        return $this;
    }

}

