<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/sigchain.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.SigChainElem</code>
 */
class SigChainElem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>bytes next_pubkey = 2;</code>
     */
    protected $next_pubkey = '';
    /**
     * Generated from protobuf field <code>bool mining = 3;</code>
     */
    protected $mining = false;
    /**
     * Generated from protobuf field <code>bytes signature = 4;</code>
     */
    protected $signature = '';
    /**
     * Generated from protobuf field <code>.protos.SigAlgo sig_algo = 5;</code>
     */
    protected $sig_algo = 0;
    /**
     * Generated from protobuf field <code>bytes vrf = 6;</code>
     */
    protected $vrf = '';
    /**
     * Generated from protobuf field <code>bytes proof = 7;</code>
     */
    protected $proof = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $next_pubkey
     *     @type bool $mining
     *     @type string $signature
     *     @type int $sig_algo
     *     @type string $vrf
     *     @type string $proof
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\Sigchain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, False);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes next_pubkey = 2;</code>
     * @return string
     */
    public function getNextPubkey()
    {
        return $this->next_pubkey;
    }

    /**
     * Generated from protobuf field <code>bytes next_pubkey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPubkey($var)
    {
        GPBUtil::checkString($var, False);
        $this->next_pubkey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool mining = 3;</code>
     * @return bool
     */
    public function getMining()
    {
        return $this->mining;
    }

    /**
     * Generated from protobuf field <code>bool mining = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setMining($var)
    {
        GPBUtil::checkBool($var);
        $this->mining = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 4;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.SigAlgo sig_algo = 5;</code>
     * @return int
     */
    public function getSigAlgo()
    {
        return $this->sig_algo;
    }

    /**
     * Generated from protobuf field <code>.protos.SigAlgo sig_algo = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSigAlgo($var)
    {
        GPBUtil::checkEnum($var, \Protos\SigAlgo::class);
        $this->sig_algo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes vrf = 6;</code>
     * @return string
     */
    public function getVrf()
    {
        return $this->vrf;
    }

    /**
     * Generated from protobuf field <code>bytes vrf = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setVrf($var)
    {
        GPBUtil::checkString($var, False);
        $this->vrf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes proof = 7;</code>
     * @return string
     */
    public function getProof()
    {
        return $this->proof;
    }

    /**
     * Generated from protobuf field <code>bytes proof = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setProof($var)
    {
        GPBUtil::checkString($var, False);
        $this->proof = $var;

        return $this;
    }

}

