<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/transaction.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.Subscribe</code>
 */
class Subscribe extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes subscriber = 1;</code>
     */
    protected $subscriber = '';
    /**
     * Generated from protobuf field <code>string identifier = 2;</code>
     */
    protected $identifier = '';
    /**
     * Generated from protobuf field <code>string topic = 3;</code>
     */
    protected $topic = '';
    /**
     * Generated from protobuf field <code>uint32 bucket = 4 [deprecated = true];</code>
     */
    protected $bucket = 0;
    /**
     * Generated from protobuf field <code>uint32 duration = 5;</code>
     */
    protected $duration = 0;
    /**
     * Generated from protobuf field <code>string meta = 6;</code>
     */
    protected $meta = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $subscriber
     *     @type string $identifier
     *     @type string $topic
     *     @type int $bucket
     *     @type int $duration
     *     @type string $meta
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes subscriber = 1;</code>
     * @return string
     */
    public function getSubscriber()
    {
        return $this->subscriber;
    }

    /**
     * Generated from protobuf field <code>bytes subscriber = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriber($var)
    {
        GPBUtil::checkString($var, False);
        $this->subscriber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identifier = 2;</code>
     * @return string
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Generated from protobuf field <code>string identifier = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string topic = 3;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 bucket = 4 [deprecated = true];</code>
     * @return int
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Generated from protobuf field <code>uint32 bucket = 4 [deprecated = true];</code>
     * @param int $var
     * @return $this
     */
    public function setBucket($var)
    {
        GPBUtil::checkUint32($var);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 5;</code>
     * @return int
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkUint32($var);
        $this->duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string meta = 6;</code>
     * @return string
     */
    public function getMeta()
    {
        return $this->meta;
    }

    /**
     * Generated from protobuf field <code>string meta = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMeta($var)
    {
        GPBUtil::checkString($var, True);
        $this->meta = $var;

        return $this;
    }

}

