<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protos/transaction.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protos.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protos.UnsignedTx unsigned_tx = 1;</code>
     */
    protected $unsigned_tx = null;
    /**
     * Generated from protobuf field <code>repeated .protos.Program programs = 2;</code>
     */
    private $programs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protos\UnsignedTx $unsigned_tx
     *     @type \Protos\Program[]|\Google\Protobuf\Internal\RepeatedField $programs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobuf\Protos\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.UnsignedTx unsigned_tx = 1;</code>
     * @return \Protos\UnsignedTx
     */
    public function getUnsignedTx()
    {
        return $this->unsigned_tx;
    }

    /**
     * Generated from protobuf field <code>.protos.UnsignedTx unsigned_tx = 1;</code>
     * @param \Protos\UnsignedTx $var
     * @return $this
     */
    public function setUnsignedTx($var)
    {
        GPBUtil::checkMessage($var, \Protos\UnsignedTx::class);
        $this->unsigned_tx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Program programs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrograms()
    {
        return $this->programs;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Program programs = 2;</code>
     * @param \Protos\Program[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrograms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Program::class);
        $this->programs = $arr;

        return $this;
    }

}

